import numpy as np
x=np.array([1,2,3,4,5])
print(x)
y=np.array([6,7,8,9,10])
print(y)    
print(np.sqrt(x))
print(np.sqrt(y))
print(np.power(x,2))
print(np.power(y,2))        
print(np.add(x,y))
print(np.subtract(x,y)) 
print(np.multiply(x,y))
print(np.divide(x,y))   
