import numpy as np
import matplotlib.pyplot as plt
arr=np.array([30,40,50,60])
print(arr)
print(type(arr))
print(arr.shape)
arr1=arr.reshape(2,2)
print(arr1)
arr2=np.array([1,4])
print(arr2)
arr2=arr2.reshape(2,1)
print(arr2)
arr3=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr3)
print(np.sum(arr3))
print(np.mean(arr3))
print(np.median(arr3))
print(np.std(arr3))
print(np.log(arr3))
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(np.dot(arr1, arr2))
arr6=np.array([[1,2,3],[4,5,6]])
print(np.sqrt(arr6))
print(np.sum(arr6))
print(np.mean(arr6))
print(np.median(arr6))
print(np.std(arr6))
print(np.log(arr6))
arr7=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr7)
print(arr7.shape)
print(arr7[0][1])
print(arr7[1][0])
print(arr7[1:2:])
print(arr7[:,0,:])
arr7[0,0]=100
print(arr7)
arr7[1,1,2]=200
print(arr7)
plt.plot(arr)
plt.xlabel('Index')
plt.ylabel('Value')
plt.title('Line Plot of Array')
plt.show()
plt.scatter(range(len(arr)), arr, color='red', marker='x', s=100)
plt.xlabel('Index')
plt.ylabel('Value')
plt.title('Scatter Plot of Array')
plt.show()
plt.bar(range(len(arr)), arr, color='red', width=0.5)
plt.xlabel('Index')
plt.ylabel('Value')
plt.title('Bar Plot of Array')
plt.show()