import numpy as np
import matplotlib.pyplot as plt
arr=[30,40,50,60]
print(arr)
arr1=max(arr)
print(arr1) 
arr2=min(arr)
print(arr2)
arr3=np.mean(arr)
print(arr3)
arr4=np.median(arr)
print(arr4)
diff=np.diff(arr)
print("day to day changes", diff)
fehrenheit=np.array(arr)*9/5+32
print("fehrenheit", fehrenheit)
print("max", max(arr))
print("min", min(arr))
print("mean", np.mean(arr))
print("median", np.median(arr)) 
print("standard deviation", np.std(arr))
print("variance", np.var(arr))
print("percentiles", np.percentile(arr, [25, 50, 75]))
print("correlation coefficient", np.corrcoef(arr, fehrenheit))
plt.plot(arr)
plt.xlabel('Index')
plt.ylabel('Temperature')
plt.title('Temperature Plot')
plt.show()

